<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Insert title here</title>
	</head>
	<body>
		<div style="float:left; margin: 300px; width:400px; height:100px; background:#dadada; text-align:center; border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px">
			<form method="post" action="" style="margin-top:35px">
				Nome:
				<input name="nome" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				<input type="submit" value="Enviar">
			</form>
		</div>
	</body>
</html>