<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		<div style="float:left; margin: 300px; width:400px; height:300px; background:#dadada; text-align:center; border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px">
			<form method="post" action="" style="margin-top:35px">
				<p>
					Nome:
					<input name="titulo" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				</p>
				<p>
					Edição:
					<input name="edicao" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				</p>
				<p>
					Ano:
					<input name="ano" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				</p>
				<p>
					Paginas:
					<input name="paginas" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				</p>
				<p>
					Quantidade:
					<input name="quantidade" type="text" style="border-radius:10px; -moz-border-radius:10px; -webkit-border-radius:10px; padding:3px;">
				</p>
				<input type="submit" value="Enviar">
			</form>
		</div>
	</body>
</html>